[uwsgi]
chdir = /home/odoo/react_server/flaskProject
module = wsgi:app
#home = /home/odoo/react_server/flaskProject
plugins = python3
master = true
processes = 2
socket = /home/odoo/react_server/flaskProject/app.sock
chmod-socket = 664
vacuum = true

#die-on-term = true
